PtdLesson06.CF/Models/PtdBook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PtdLesson06.CF.Models
{
    public class PtdBook
    {

        [Key]
        public int PtdId { get; set; }
        public string PtdBookId { get; set; }
        public string PtdTitle { get; set; }
        public string PtdAuthor { get; set; }
        public int PtdYear { get; set; }
        public string PtdPulisher { get; set; }
        public string PtdPicture { get; set; }
        public int PtdCategoryId { get; set; }
        //thuoc tinh quan he
        public virtual PtdCategory PtdCategory { get; set; }
    }
}

PtdLesson06.CF/Models/PtdBookStore.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace PtdLesson06.CF.Models
{
    public class PtdBookStore : DbContext
    {
        public PtdBookStore() : base("PtdBookStoreConnectionString") { }
        //khai bao cac thuoc tinh tuong ung voi bang trong csdl
        public DbSet<PtdCategory> PtdCategories { get; set; }
        public DbSet<PtdBook> PtdBooks { get; set; }
    }
}

PtdLesson06.CF/Models/PtdCategory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PtdLesson06.CF.Models
{
    public class PtdCategory
    {
        [Key]
        public int PtdId { get; set; }
        public string PtdCategoryName { get; set; }
        // thuoc tinh quan he
        public virtual ICollection<PtdBook> PtdBooks { get; set; }
    }
}

PtdLesson06.CF/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PtdLesson06.CF.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PtdLesson06.CF/Controllers/PtdBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PtdLesson06.CF.Models;

namespace PtdLesson06.CF.Controllers
{
    public class PtdBooksController : Controller
    {
        private PtdBookStore db = new PtdBookStore();

        // GET: PtdBooks
        public ActionResult Index()
        {
            return View(db.PtdBooks.ToList());
        }

        // GET: PtdBooks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PtdBook ptdBook = db.PtdBooks.Find(id);
            if (ptdBook == null)
            {
                return HttpNotFound();
            }
            return View(ptdBook);
        }

        // GET: PtdBooks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PtdBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PtdId,PtdBookId,PtdTitle,PtdAuthor,PtdYear,PtdPulisher,PtdPicture,PtdCategoryId")] PtdBook ptdBook)
        {
            if (ModelState.IsValid)
            {
                db.PtdBooks.Add(ptdBook);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ptdBook);
        }

        // GET: PtdBooks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PtdBook ptdBook = db.PtdBooks.Find(id);
            if (ptdBook == null)
            {
                return HttpNotFound();
            }
            return View(ptdBook);
        }

        // POST: PtdBooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PtdId,PtdBookId,PtdTitle,PtdAuthor,PtdYear,PtdPulisher,PtdPicture,PtdCategoryId")] PtdBook ptdBook)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ptdBook).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ptdBook);
        }

        // GET: PtdBooks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PtdBook ptdBook = db.PtdBooks.Find(id);
            if (ptdBook == null)
            {
                return HttpNotFound();
            }
            return View(ptdBook);
        }

        // POST: PtdBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PtdBook ptdBook = db.PtdBooks.Find(id);
            db.PtdBooks.Remove(ptdBook);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PtdLesson06.CF/Controllers/PtdCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PtdLesson06.CF.Models;

namespace PtdLesson06.CF.Controllers
{
    public class PtdCategoriesController : Controller
    {
        private static PtdBookStore ptdDb;
        public PtdCategoriesController()
        {
            ptdDb = new PtdBookStore();
        }
        // GET: PtdCategories
        public ActionResult PtdIndex()
        {
            /*
             * khoi tao DbContext
             * Ef tim thong tin ket noi
             * sau do tao csdl
             */
            //PtdBookStore ptdDb = new PtdBookStore();
            var ptdCategories = ptdDb.PtdCategories.ToList();
            return View(ptdCategories);
        }
        public ActionResult PtdCreate()
        {
            var ptdCategory = new PtdCategory();
            return View(ptdCategory);
        }
        [HttpPost]
        public ActionResult PtdCreate(PtdCategory ptdCategory)
        {
            ptdDb.PtdCategories.Add(ptdCategory);
            ptdDb.SaveChanges();
            return RedirectToAction("PtdIndex");
        }
    }
}

PtdLesson06.CF/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PtdLesson06.CF/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PtdLesson06.CF/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PtdLesson06.CF/Views/PtdBooks/Create.cshtml
@model PtdLesson06.CF.Models.PtdBook

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PtdBook</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PtdBookId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdBookId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdBookId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PtdTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PtdAuthor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdAuthor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdAuthor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PtdYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PtdPulisher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdPulisher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdPulisher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PtdPicture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdPicture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdPicture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PtdCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdCategoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PtdLesson06.CF/Views/PtdBooks/Delete.cshtml
@model PtdLesson06.CF.Models.PtdBook

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PtdBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PtdBookId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdBookId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PtdTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PtdAuthor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdAuthor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PtdYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PtdPulisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdPulisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PtdPicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdPicture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PtdCategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdCategoryId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PtdLesson06.CF/Views/PtdBooks/Details.cshtml
@model PtdLesson06.CF.Models.PtdBook

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PtdBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PtdBookId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdBookId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PtdTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PtdAuthor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdAuthor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PtdYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PtdPulisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdPulisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PtdPicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdPicture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PtdCategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PtdCategoryId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PtdId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PtdLesson06.CF/Views/PtdBooks/Edit.cshtml
@model PtdLesson06.CF.Models.PtdBook

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PtdBook</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PtdId)

        <div class="form-group">
            @Html.LabelFor(model => model.PtdBookId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdBookId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdBookId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PtdTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PtdAuthor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdAuthor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdAuthor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PtdYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PtdPulisher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdPulisher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdPulisher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PtdPicture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdPicture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdPicture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PtdCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdCategoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PtdLesson06.CF/Views/PtdBooks/Index.cshtml
@model IEnumerable<PtdLesson06.CF.Models.PtdBook>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PtdBookId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PtdTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PtdAuthor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PtdYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PtdPulisher)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PtdPicture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PtdCategoryId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PtdBookId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PtdTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PtdAuthor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PtdYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PtdPulisher)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PtdPicture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PtdCategoryId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PtdId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PtdId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PtdId })
        </td>
    </tr>
}

</table>

PtdLesson06.CF/Views/PtdCategories/PtdCreate.cshtml
@model PtdLesson06.CF.Models.PtdCategory

@{
    ViewBag.Title = "PtdCreate";
}

<h2>PtdCreate</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PtdCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PtdCategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PtdCategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PtdCategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PtdLesson06.CF/Views/PtdCategories/PtdIndex.cshtml
@model IEnumerable<PtdLesson06.CF.Models.PtdCategory>

@{
    ViewBag.Title = "PtdIndex";
}

<h2>PtdIndex</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PtdCategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PtdCategoryName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PtdId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PtdId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PtdId })
        </td>
    </tr>
}

</table>

PtdLesson06.CF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pham Thanh Dat</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pham Thanh Dat", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("PTD: Category", "PtdIndex", "PtdCategories")</li>
                    <li>@Html.ActionLink("PTD: Book", "Index", "PtdBooks")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Pham Thanh Dat</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>